### ISSUE TITLE
cdk import doesn't include API level for `Spec`s schema

### ISSUE THREAD

**Issue by foriequal0** [cdk8s-team/cdk8s-cli#45]
### Description of the bug:
imported `Spec`s also should have API levels.

For example, `HorizontalPodAutoscalerSpec` have been changed from v1 ([v1](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#horizontalpodautoscalerspec-v1-autoscaling), [v2beta2](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#horizontalpodautoscalerspec-v2beta2-autoscaling))

I understand that V1 props doesn't have API level postfix. The generated class seems to be right.
```ts
export interface KubeHorizontalPodAutoscalerProps {
  readonly metadata?: ObjectMeta;
  readonly spec?: HorizontalPodAutoscalerSpec;
}
```

I expected that the spec should be `HorizontalPodAutoscalerSpecV2Beta2` for v2beta2, but cdk import generated this:
```ts
export interface KubeHorizontalPodAutoscalerV2Beta2Props {
  readonly metadata?: ObjectMeta;
  readonly spec?: HorizontalPodAutoscalerSpec;
}
```

Actually, `HorizontalPodAutoscalerSpec`'s comment says it is generated from v2beta2, not v1.
```ts
/**
 * HorizontalPodAutoscalerSpec describes the desired functionality of the HorizontalPodAutoscaler.
 *
 * @schema io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerSpec
 */
export interface HorizontalPodAutoscalerSpec {
```

There should be `HorizontalPodAutoscalerSpec`, `HorizontalPodAutoscalerSpecV2Beta1`, `HorizontalPodAutoscalerSpecV2Beta2`.

### Reproduction Steps:

```shell
cdk import k8s
```

### Error Log:
No error logs

### Environment:
  - **Framework Version**: v1.0.0-beta.3
  - **OS**: Windows 10, WSL 1, Ubuntu 20.10

### Other:

--- 

This is :bug: Bug Report

**Comment by Chriscbr** [comment]
I think this issue and #28 are closely related. The bug is still present - `cdk8s import k8s` is generating three different versions API objects each with its own versioned props interface (this is good):
```
KubeHorizontalPodAutoscaler
KubeHorizontalPodAutoscalerV2Beta1
KubeHorizontalPodAutoscalerV2Beta2
KubeHorizontalPodAutoscalerProps
KubeHorizontalPodAutoscalerV2Beta1Props
KubeHorizontalPodAutoscalerV2Beta2Props
```
... but each props interface is referring to the same `HorizontalPodAutoscalerSpec` interface (incorrect behavior).

At a high level, I believe the root cause is that the internal logic for adding version postfixes to type names is only being applied to API object classes and their props types, but not to any of the non-API object types. Fixing this seems a little tricky because of how we are using json2jsii. In `cdk8s import`, we manually emit code for the API object types and their props types (with custom names), but the emitting non-API object types is handled automatically (implicitly) by json2jsii.

json2jsii does provide a mechanism for creating "type aliases" which could be used to solve this. For example, when providing all of the definitions of the schema, we could write something to the effect of:

```typescript
typeGen.addDefinition('FooV2', fooSchema);
typeGen.addAlias('io.k8s.api.v2.foo', 'FooV2');
typeGen.emitType('FooV2', undefined, 'io.k8s.api.v2.foo');
```

This way, all of the references throughout the definitions schema to `#/definitions/io.k8s.api.v2.foo` will still be valid, while they will be rendered as `FooV2`. Ideally, I think we'd like to retain the current way TypeScript docstrings are rendered, so that they are annotated with `@schema io.k8s.api.v2.Foo`.

In addition to the above, the CRDs import process doesn't add version names properly, so some refactoring would be needed so that k8s and CRDs add version postfixes to names in the same way.
